### ISSUE TITLE
Feature request: Scrobble with existing mbid tag

### ISSUE THREAD

**Issue by jtpavlock** [karaluh/ScrobblerBrainz#7] opened 2020-06-08 00:51 UTC
[beets](https://beets.io/), a popular music organizer, actually sets track recording ids under the tag `MUSICBRAINZ_TRACKID` that you may be able to use to scrobble

**Comment by karaluh** [comment] 2020-06-08 06:44
Thanks for the request, MBID scrobbling is something I would like to very much like to implement.

**Comment by jtpavlock** [comment] 2020-06-21 20:34
It seems the musicbee api doesn't allow access to tags unless they're officially supported by musicbee. I bumped an old thread concerning this [here](https://getmusicbee.com/forum/index.php?topic=12916.0)

**Comment by karaluh** [comment] 2020-06-22 07:16
That is correct. There is a workaround, however. Custom tags can be defined to make MBIDs available with the API, but this solution is not pretty.

I don't expect this feature to be implemented in MusicBee anytime soon (if ever) and I plan to use [TagLib](https://taglib.org/) for this.

**Comment by ghost** [comment] 2022-02-08 14:32
I might have a look at tackling this as well. Would [TagLibSharp](https://github.com/mono/taglib-sharp) suffice?

**Comment by karaluh** [comment] 2022-02-08 17:40
Yes, it looks very good.

**Comment by Viktini** [comment] 2022-02-16 13:22
Ran into some issues implementing this with the current version of TagLibSharp, would like to know if you're okay with this going forward:

- The solution targets .NET 4.0 but TagLibSharp requires .NET 4.5 / 4.6. Don't want to commit a change to the target version without discretion.
- TagLibSharp conflicts with the standard .NET libraries with certain namespaces - `File` and `TextBox`. Easy fix, just declare the intended namespace - e.g. `System.IO.File` vs. `TagLib.File`
- The latest release of TagLibSharp only retrieves the first entry in the tag when using the artist MBIDs _by design._ ListenBrainz's API documentation states that if there are multiple artist IDs they should be submitted. Directly grabbing the tags is a workaround for this, but ASF and MPEG4 tags (for Windows Media and AAC respectively) don't have any workarounds to grab multiple IDs. [There have been merged PRs there that fix this issue](https://github.com/mono/taglib-sharp/pull/253), including for MPEG4, but they haven't provided a new package release yet.
  - Worth pointing out that MusicBee can't even see split MPEG4 tags. The artist ID tag doesn't appear on its Tag Inspector. I'll raise that issue on the forums, but MPEG4 seems to be problematic in general (e.g. Quod Libet can see them but cannot save them, foobar2000 only sees the last tag)

If you're fine with the workarounds I can go ahead with that. I can submit everything except the artist tags when scanning ASF and MPEG4 tags and let MessyBrainz handle it on their end, since the other IDs can be retrieved and submitted just fine. I did a test submit that omits the artist ID entirely, and the artist gets automatically linked once it's submitted. Looking at the raw JSON, it manages to link every artist when multiple artists are present on the submitted release.

**Comment by ghost** [comment] 2022-04-11 20:53
Apologies for my past ramblings. I felt like it was just spam without the code, and I took March away from working on the changes for personal reasons. That being said, I've decided to finally implement this using TagLib#. Everything is available here, including now playing. https://github.com/Viktini/ScrobblerBrainz/tree/mbid-submit

Some things to point out:
- I had to bump the required .NET version to 4.6.2. [TagLib#'s current minimum supported version on NuGet is 4.5](https://www.nuget.org/packages/TagLibSharp/), and I noticed in their commits that [4.6.2 will be the new minimum](https://github.com/mono/taglib-sharp/commit/8eb9957dd7cf3dde43d187fe5f414201b8b81ee9). This is the minimum for Visual Studio 2022, as well, for what it's worth, and MusicBee has [bumped its requirements to 4.8](https://getmusicbee.com/forum/index.php?topic=36464.msg200412) as of 3.5.
- Where I can, I was able to grab multiple MBIDs, however due to limitations and inconsistencies in the current stable version of TagLib#, this wasn't possible on M4A/MP4 (Apple) or WMA/ASF tags. I asked on the MetaBrainz board and they said [it's fine to submit one artist MBID](https://community.metabrainz.org/t/handling-library-limitations-send-one-artist-mbid-or-none-at-all/580425/2) as long as recording MBIDs are retrievable, which on all tag formats supported by both MusicBee and TagLib#, it is.
- .NET 4.6.2 works on WINE, and so does the plugin with the `mbid-submit` code (tested on Arch Linux), albeit with some bugs. I wouldn't support this use case myself (being a Linux user) but, the fact it _mostly_ works is nice.

**Closed as completed** 2022-12-18 17:29 UTC
Labels: enhancement
